import type { ScanRule } from "@/types/scan";

export const toolPoisoningRules: ScanRule[] = [
  {
    id: "TP001",
    category: "tool-poisoning",
    title: "Hidden HTML/XML tags in tool description",
    description:
      "Tool descriptions containing hidden HTML or XML tags can inject invisible directives to manipulate LLM behavior.",
    severity: "critical",
    pattern: /<hidden[^>]*>|<\/hidden>|<invisible[^>]*>|<secret[^>]*>/gi,
    remediation: "Remove hidden HTML/XML tags from tool descriptions. Descriptions must be plain text.",
  },
  {
    id: "TP002",
    category: "tool-poisoning",
    title: "HTML comment injection in tool description",
    description:
      "HTML comments in tool descriptions may contain hidden instructions intended to influence LLM reasoning.",
    severity: "critical",
    pattern: /<!--[\s\S]*?-->/g,
    remediation: "Remove HTML comments from description strings. Use source code comments instead.",
  },
  {
    id: "TP003",
    category: "tool-poisoning",
    title: "Invisible unicode characters in tool description",
    description:
      "Zero-width and invisible unicode characters can hide malicious text within tool descriptions.",
    severity: "critical",
    pattern: /[\u200B\u200C\u200D\uFEFF\u2060\u2061\u2062\u2063\u2064]/g,
    remediation: "Remove zero-width/invisible unicode characters. Run descriptions through a unicode sanitizer.",
  },
  {
    id: "TP004",
    category: "tool-poisoning",
    title: "Directive injection in tool description",
    description:
      "Phrases like 'ignore previous instructions' or 'disregard' attempt to override LLM system prompts via tool metadata.",
    severity: "critical",
    pattern:
      /\b(ignore\s+(previous|prior|above|all)\s+(instructions?|prompts?|rules?)|disregard\s+(previous|prior|above|all)|override\s+(previous|system|safety)|forget\s+(previous|prior|all|your)\s+(instructions?|rules?|prompts?))\b/gi,
    remediation: "Remove prompt-override phrases from descriptions. Tool metadata must not contain behavioral directives.",
  },
  {
    id: "TP005",
    category: "tool-poisoning",
    title: "Cross-tool shadowing of system commands",
    description:
      "Tool names mimicking built-in system tools (e.g., 'bash', 'shell', 'terminal') can trick the LLM into routing actions to a malicious handler.",
    severity: "high",
    pattern:
      /(?:name|tool_name|toolName)\s*[:=]\s*["'`](bash|shell|terminal|cmd|exec|system|admin|sudo|root|eval|run_command|execute)["'`]/gi,
    remediation: "Rename the tool to avoid colliding with system commands (bash, shell, exec, etc.).",
  },
  {
    id: "TP006",
    category: "tool-poisoning",
    title: "Prompt injection via description field",
    description:
      "Tool descriptions containing system-prompt-style directives (e.g., 'you are', 'always respond') attempt to hijack LLM behavior.",
    severity: "high",
    pattern:
      /\b(you\s+are\s+now|you\s+must\s+always|always\s+respond\s+with|act\s+as\s+if|pretend\s+you\s+are|from\s+now\s+on\s+you)\b/gi,
    remediation: "Remove system-prompt-style directives from description. Descriptions should explain the tool's function, not instruct the model.",
  },
  {
    id: "TP007",
    category: "tool-poisoning",
    title: "Base64-encoded hidden instructions in description",
    description: "Base64-encoded strings in tool descriptions may hide malicious instructions that are decoded and executed by the LLM.",
    severity: "high",
    pattern: /(?:description|desc)\s*[:=]\s*["'`][^"'`]*(?:[A-Za-z0-9+/]{40,}={0,2})[^"'`]*["'`]/g,
    remediation: "Remove Base64-encoded content from descriptions. All instructions must be in plain text.",
    owaspMcpTop10: "MCP03",
    cweIds: ["CWE-94"],
  },
  {
    id: "TP008",
    category: "tool-poisoning",
    title: "Markdown link injection in tool description",
    description: "Markdown links in descriptions can redirect LLMs to malicious resources or inject hidden context.",
    severity: "medium",
    pattern: /(?:description|desc)\s*[:=]\s*["'`][^"'`]*\[.*?\]\((?:javascript:|data:|https?:\/\/)[^)]*\)[^"'`]*["'`]/g,
    remediation: "Remove markdown links from tool descriptions. Use plain text only.",
    owaspMcpTop10: "MCP03",
    cweIds: ["CWE-94", "CWE-79"],
  },
  {
    id: "TP009",
    category: "tool-poisoning",
    title: "Excessively long tool description",
    description: "Tool descriptions over 2000 characters may hide malicious instructions in verbose text that evades human review.",
    severity: "medium",
    pattern: /(?:description|desc)\s*[:=]\s*["'`][^"'`]{2000,}["'`]/g,
    remediation: "Keep tool descriptions concise (under 500 characters). Long descriptions may hide injected content.",
    owaspMcpTop10: "MCP03",
    cweIds: ["CWE-94"],
  },
  {
    id: "TP010",
    category: "tool-poisoning",
    title: "RTL override characters in tool metadata",
    description: "Right-to-left override characters can visually disguise malicious text in tool names or descriptions.",
    severity: "critical",
    pattern: /[\u202A\u202B\u202C\u202D\u202E\u2066\u2067\u2068\u2069]/g,
    remediation: "Remove all Unicode bidirectional override characters from tool metadata.",
    owaspMcpTop10: "MCP03",
    cweIds: ["CWE-94"],
  },
  {
    id: "TP011",
    category: "tool-poisoning",
    title: "Tool description referencing other tools",
    description: "A tool description that names or references other tools may attempt cross-tool manipulation of the LLM.",
    severity: "medium",
    pattern: /(?:description|desc)\s*[:=]\s*["'`][^"'`]*(?:use\s+the\s+\w+\s+tool|call\s+\w+\s+first|before\s+using\s+this.*run\s+\w+|after\s+this.*execute\s+\w+)[^"'`]*["'`]/gi,
    remediation: "Tool descriptions must not reference or instruct use of other tools.",
    owaspMcpTop10: "MCP03",
    cweIds: ["CWE-94"],
  },
  {
    id: "TP012",
    category: "tool-poisoning",
    title: "Escaped character sequences hiding directives",
    description: "Escaped newlines, tabs, or unicode sequences in descriptions can hide instructions from human review.",
    severity: "high",
    pattern: /(?:description|desc)\s*[:=]\s*["'`][^"'`]*(?:\\n\\n|\\t\\t|\\u00[0-9a-fA-F]{2}){3,}[^"'`]*["'`]/g,
    remediation: "Remove excessive escaped character sequences from descriptions.",
    owaspMcpTop10: "MCP03",
    cweIds: ["CWE-94"],
  },
];
