import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Terms of Service for MCP Scanner, the free security scanner for Model Context Protocol servers.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl pt-20 pb-24">
      <h1 className="text-3xl font-semibold tracking-tight text-foreground mb-2">
        Terms of Service
      </h1>
      <p className="text-sm text-muted-foreground mb-12">
        Last updated: April 2026
      </p>

      <div className="space-y-12">
        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">
            Service Description
          </h2>
          <p className="text-muted leading-relaxed">
            MCP Scanner (<strong className="text-foreground">mcpscanner.cloud</strong>)
            is a free, open-source security scanning service for Model Context
            Protocol servers. It analyzes public GitHub repositories for
            vulnerability patterns and produces security grades, findings, and
            compliance reports.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">
            Acceptable Use
          </h2>
          <p className="text-muted leading-relaxed mb-3">
            You agree to use MCP Scanner responsibly. In particular, you must
            not:
          </p>
          <ul className="list-disc pl-5 text-muted leading-relaxed space-y-1.5">
            <li>
              Submit repositories you do not own or have permission to scan in
              bad faith.
            </li>
            <li>
              Attempt to circumvent rate limits or abuse the API through
              automated means beyond normal usage.
            </li>
            <li>
              Use scan results to harass, extort, or publicly shame repository
              maintainers.
            </li>
            <li>
              Interfere with or disrupt the service, its infrastructure, or other
              users.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">
            Accuracy Disclaimer
          </h2>
          <p className="text-muted leading-relaxed">
            Scan results are generated by automated static analysis and pattern
            matching. They are not a guarantee of security or a substitute for a
            professional security audit. False positives and false negatives may
            occur. You should independently verify all findings before acting on
            them.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">
            Public Leaderboard
          </h2>
          <p className="text-muted leading-relaxed">
            Scanned MCP servers are ranked on a public leaderboard by security
            grade. By submitting a repository for scanning, you acknowledge that
            the resulting grade and summary findings may appear publicly on the
            leaderboard and in search results.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">
            No Warranty
          </h2>
          <p className="text-muted leading-relaxed">
            MCP Scanner is provided{" "}
            <strong className="text-foreground">&quot;as is&quot;</strong> and{" "}
            <strong className="text-foreground">
              &quot;as available&quot;
            </strong>{" "}
            without warranties of any kind, whether express or implied, including
            but not limited to implied warranties of merchantability, fitness for
            a particular purpose, and non-infringement.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">
            Limitation of Liability
          </h2>
          <p className="text-muted leading-relaxed">
            To the fullest extent permitted by law, MCP Scanner and its
            maintainers shall not be liable for any indirect, incidental,
            special, consequential, or punitive damages, or any loss of data,
            profits, or revenue, arising out of or related to your use of the
            service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">
            Changes to These Terms
          </h2>
          <p className="text-muted leading-relaxed">
            We may update these terms from time to time. Material changes will be
            posted on this page with an updated revision date. Continued use of
            the service after changes are published constitutes acceptance of the
            revised terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">
            Contact
          </h2>
          <p className="text-muted leading-relaxed">
            For questions about these terms, contact us at{" "}
            <a
              href="mailto:legal@mcpscanner.cloud"
              className="text-brand-400 hover:underline"
            >
              legal@mcpscanner.cloud
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
